version: "3"

services:
  server-mongo-frontend:
    image: mongo
    container_name: server-mongo-frontend
    env_file:
      - ./.env.dev
    volumes:
      - ./data/server-mongo-frontend:/data/db
    restart: unless-stopped
    ports:
      - 7703:27017

  server-redis-database:
    image: redis:latest
    container_name: server-redis-database
    env_file: 
      - ./.env.dev
    volumes:
      - ./data/server-redis-database:/data
    restart: unless-stopped
    ports:
      - 7702:6379

  server-api:
    container_name: server-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: node:14
    restart: unless-stopped
    working_dir: ./backend
    depends_on:
      - server-redis-database
      - server-mongo-frontend
    ports:
      - 7701:7701
    volumes:
      - ./backend/src